#!/bin/bash
#
#

#killall ii

while [ 1 ]; do
NICK=$(pwgen -1 $((RANDOM % 13)))
echo $NICK

ii -i /tmp/$NICK/irc -s 127.0.0.1 -p 6667 -n $NICK -f $NICK &
MSG="$(echo -e "hi\nhello\n:*\ntits\nbobs" | sort -uR | head -n1)"

sleep 3
echo "/j #chat" >> /tmp/$NICK/irc/127.0.0.1/in
sleep $((RANDOM % 10))
echo "$MSG"  >> /tmp/$NICK/irc/127.0.0.1/#chat/in

sleep 1m
done


#sleep 20

exit

sleep 2
echo "hi
hi
hi" | while read A; do
        sleep 1
done



